### ISSUE TITLE
Remove "UserPro" Wordpress Plugin Dependency. 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools-2.0#1]
Website currently uses "UserPro" for the following pages:
- http://mcaprotools.com/login/
- http://mcaprotools.com/profile/

..And is also used for profile picture / avatar. 

> *I installed "Woocommerce Subscriptions" which should replace userpro.

**Comment by sgerritse** [comment]
![screen shot 2017-02-05 at 3 02 46 pm](https://cloud.githubusercontent.com/assets/10511034/22629487/0675c08a-ebb5-11e6-8743-81c5020b989e.png)

In this screenshot, I was NOT logged into any account. However, it is showing the content & menus etc. Instead of redirecting to login page / template.

------

**“Unpaid User / Guest” CAN ONLY View these pages:**

Capture Pages / Optin:
http://www.mcaprotools.com/notsleepingvideo/?ref=Username01
http://www.mcaprotools.com/losingsleep/?ref=Username02
http://www.mcaprotools.com/2kperweek/?ref=RandomUser

Landing Pages:
http://www.mcaprotools.com/whatismca/
http://www.mcaprotools.com/benefits/
http://www.mcaprotools.com/testimonials/

**Comment by juandlr** [comment]
this is fixed now
