### ISSUE TITLE
On Desktop, the menu "Lock Icons" still showing

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools-2.0#13]
After the user unlocked each section, it should remove the "lock icons" from the menu.

**Comment by sgerritse** [comment]
Also make sure that the lock icons work the same on mobile too.

**Comment by juandlr** [comment]
this seems to work fine, http://jmp.sh/KSZjvjK, the locks disappear when you mark the lesson complete, let me know if its somewhere else

**Comment by sgerritse** [comment]
Log into user (felontofortune / asher187) 

He has completed all the training courses but the "Locks" still show.
