### ISSUE TITLE
Convert All Pages from "Page Editor" to "Page Template"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools-2.0#3]
For some reason, the original developer of this project left all the code in the "Page Editor" instead of creating a "page template" for each page.

These are the pages that should be "page templates":
- http://mcaprotools.com/benefits/
- http://mcaprotools.com/ (Dashboard)
- http://mcaprotools.com/2kperweek/
- http://mcaprotools.com/hangout/
- http://mcaprotools.com/login/
- http://mcaprotools.com/whatismca/
- http://mcaprotools.com/mcatools/
- http://mcaprotools.com/takeover/
- http://mcaprotools.com/pushstart/
- http://mcaprotools.com/what-is-mca/
- http://mcaprotools.com/losingsleep/
- http://mcaprotools.com/notsleepingvideo/

**Comment by juandlr** [comment]
http://mcaprotools.com/mcatools/ - this page is missing
