### ISSUE TITLE
Dashboard should be Template / Redirect

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools-2.0#6]
Currently "Dashboard" page doesn't have its own page template:
http://mcaprotools.com/wp-admin/post.php?post=6&action=edit

...Also noticed that even though the "dashboard" page is set for homepage:
![screen shot 2017-02-05 at 3 07 55 pm](https://cloud.githubusercontent.com/assets/10511034/22629482/e617700e-ebb4-11e6-8e85-a503f3267265.png)

It keeps redirecting user to  "training hub". 

----

The Dashboard should be showing this menu:
![screen shot 2017-02-05 at 2 47 51 pm](https://cloud.githubusercontent.com/assets/10511034/22629520/8e41be4c-ebb5-11e6-80c9-87d588f093af.png)

As well as have this under the "Welcome Video" on the Dashboard:
![screen shot 2017-02-05 at 3 13 19 pm](https://cloud.githubusercontent.com/assets/10511034/22629525/b17377c0-ebb5-11e6-9191-492b04e1e93d.png)

**Comment by juandlr** [comment]
My profile is a userpro function, i can create this page, i tought you said you didnt need profile
